# Generated by Django 5.0.6 on 2025-04-22 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMaster',
            fields=[
                ('DocumentTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('DocumentTypeName', models.CharField(max_length=100)),
                ('DocumentType', models.CharField(choices=[('Applicant Shared', 'Applicant Shared'), ('Admin Shared', 'Admin Shared')], max_length=20)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(default='system', max_length=100)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UpdatedBy', models.CharField(default='system', max_length=100)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'db_table': 'DocumentMaster',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DocumentId', models.AutoField(primary_key=True, serialize=False)),
                ('ClientId', models.IntegerField(default=1)),
                ('CompanyId', models.IntegerField(default=1)),
                ('DocumentName', models.CharField(max_length=255)),
                ('UserDocuName', models.CharField(blank=True, max_length=255, null=True)),
                ('OriginalName', models.CharField(default='', max_length=255)),
                ('FilePath', models.CharField(max_length=255)),
                ('DocumentStatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archived', 'Archived'), ('Latest', 'Latest'), ('Deprecated', 'Deprecated')], default='Pending', max_length=20)),
                ('VisibleToCust', models.BooleanField(default=False)),
                ('Version', models.IntegerField(default=1)),
                ('VersionDate', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(default='system', max_length=100)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UpdatedBy', models.CharField(default='system', max_length=100)),
                ('CustomerId', models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('DocumentTypeId', models.ForeignKey(db_column='DocumentTypeId', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentmaster')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'Documents',
            },
        ),
    ]
