# Generated by Django 5.0.6 on 2025-05-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0005_remove_lineofbusiness_schema_name'),
        ('subscription_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='line_of_business',
            field=models.ForeignKey(blank=True, help_text='The line of business this subscription plan belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plans', to='ecomm_superadmin.lineofbusiness'),
        ),
    ]
