# Generated by Django 5.0.6 on 2025-05-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0002_subscriptionplan_line_of_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('weekly', 'Weekly'), ('one_time', 'One Time')], default='monthly', help_text='Billing cycle for the subscription plan', max_length=20),
        ),
    ]
