# Generated by Django 5.0.6 on 2025-06-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0003_subscriptionplan_billing_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One Time'), ('weekly', 'Weekly')], help_text='Billing cycle for the subscription plan', max_length=20),
        ),
    ]
