# Generated by Django 4.2.10 on 2025-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentlocation',
            name='location_type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('STORE', 'Retail Store'), ('FULFILLMENT_CENTER', 'Fulfillment Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('ADD', 'Addition'), ('SUB', 'Subtraction'), ('RES', 'Reservation'), ('REL_RES', 'Release Reservation'), ('NON_SALE', 'Mark Non-Saleable'), ('RECV_PO', 'Receive Purchase Order'), ('SHIP_ORD', 'Ship Sales Order'), ('RET_STOCK', 'Return to Stock'), ('RET_NON_SALE', 'Return to Non-Saleable'), ('HOLD', 'Place on Hold'), ('REL_HOLD', 'Release from Hold'), ('CYCLE', 'Cycle Count Adjustment'), ('INIT', 'Initial Stock Load')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved (Order Pending)'), ('EXPIRED', 'Expired'), ('QUARANTINE', 'In Quarantine'), ('DAMAGED', 'Damaged / Non-Saleable')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='serializedinventory',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved (Order Pending)'), ('SOLD', 'Sold (Shipped)'), ('IN_TRANSIT', 'In Transit (Transfer)'), ('RETURNED', 'Returned (Pending Inspection)'), ('DAMAGED', 'Damaged / Non-Saleable')], db_index=True, default='AVAILABLE', max_length=20),
        ),
    ]
