# settings.py
"""
Django settings for KeyProductSettings project.

Generated by 'django-admin startproject' using Django 4.2.10.
Modified for django_tenants multi-tenancy.
"""

from pathlib import Path
from datetime import timedelta
import os # Recommended for environment variables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Secrets and Debugging ---
# SECURITY WARNING: keep the secret key used in production secret!
# Consider using environment variables for secrets
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-8f_ln2-aly%)49y!u=*en82-i$feq0(6#y5*sbu3(9*6p4)ysg') # Example using os.environ

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

INTERNAL_API_SECRET = 'secret'      # Key for backend to backend api calls of Tenant

APPLICATION_MIGRATION_BACKEND_ENDPOINT = "api/tenant/migrate/"

# --- Application definition ---

# Define Custom User Model *before* app lists
AUTH_USER_MODEL = 'ecomm_superadmin.User'

# Combined INSTALLED_APPS for development
# Define which apps are shared (in public schema) and which are tenant-specific
SHARED_APPS = (
    'django_tenants',  # mandatory
    'ecomm_superadmin',  # app containing your tenant model
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',     # Links to ecomm_superadmin.User (shared)
    'rest_framework_simplejwt', # Links to ecomm_superadmin.User (shared)
  
    'subscription_plan',  # Add the new app
    'external_tenants',  # Add the new app
        'shared',  # App for shared utilities and location APIs

    
)

TENANT_APPS = (
    'ecomm_tenant.ecomm_tenant_admins',
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

# --- Middleware ---
# Order matters! TenantMiddleware must be first
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # This should be at the top
    'ecomm_tenant.ecomm_tenant_admins.middleware.TenantRoutingMiddleware',  # Custom middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'ecomm_superadmin.middleware.CSRFExemptAPIMiddleware',  # Our custom CSRF exempt middleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

################## GCS Cred #####################
GCS_BUCKET_NAME = "turtle_qrosity"
GCS_PROJECT_ID = "turtle-software-qrosity"
GCS_SERVICE_ACCOUNT_PATH = os.path.join(BASE_DIR, "services/gcp-service-account.json")

# --- Templates ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --- WSGI ---
WSGI_APPLICATION = 'KeyProductSettings.wsgi.application'


# --- Database ---
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Configure for PostgreSQL with django_tenants
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend', # Correct engine for django_tenants
        'NAME': os.environ.get('DB_NAME', 'iam_login'), # Use lowercase to match existing DB
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Qu1ckAss1st@123'),
        'HOST': os.environ.get('DB_HOST', 'localhost'), 
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# --- Password validation ---
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Internationalization ---
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# --- Media files (user-uploaded content) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- Static files (CSS, JavaScript, Images) ---
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Add a directory for shared static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# --- Default primary key field type ---
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Rest Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# --- Simple JWT ---
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    # 'SIGNING_KEY': SECRET_KEY,
    'SIGNING_KEY': 'abc123',
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}





#################### Rabbit MQ ###############################

TIME_ZONE = "Asia/Kolkata"
# RabbitMQ Settings
RABBITMQ_API_URL = os.environ.get('RABBITMQ_API_URL', 'http://localhost:15672')
RABBITMQ_API_USER = os.environ.get('RABBITMQ_API_USER', 'guest')
RABBITMQ_API_PASSWORD = os.environ.get('RABBITMQ_API_PASSWORD', 'guest')
RABBITMQ_VHOST = os.environ.get('RABBITMQ_VHOST', '/')
RABBITMQ_EXCHANGE_NAME = os.environ.get('RABBITMQ_EXCHANGE_NAME', 'cns_direct_exchange')
CNS_STATUS_EXCHANGE_NAME = os.environ.get('CNS_STATUS_EXCHANGE_NAME', 'cns_status_exchange')
RABBITMQ_TENANT_USER = os.environ.get('RABBITMQ_TENANT_USER', 'guest')

# Celery Settings
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://guest:guest@localhost:5672//')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE


######################### Celery ######################

# --- Celery Configuration ---
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://guest:guest@localhost:5672//')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'rpc://')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 15 * 60
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_CREATE_MISSING_QUEUES = True
CELERY_TASK_DEFAULT_EXCHANGE = os.environ.get('RABBITMQ_EXCHANGE_NAME', 'cns_direct_exchange')
CELERY_TASK_QUEUE_MAX_PRIORITY = 10
CELERY_TASK_DEFAULT_DELIVERY_MODE = 'persistent'

# --- RabbitMQ Management API Configuration ---
RABBITMQ_API_URL = os.environ.get('RABBITMQ_API_URL', 'http://localhost:15672')
RABBITMQ_API_USER = os.environ.get('RABBITMQ_API_USER', 'guest')
RABBITMQ_API_PASSWORD = os.environ.get('RABBITMQ_API_PASSWORD', 'guest')
RABBITMQ_VHOST = os.environ.get('RABBITMQ_VHOST', '%2F')  # URL-encoded '/'
RABBITMQ_EXCHANGE_NAME = os.environ.get('RABBITMQ_EXCHANGE_NAME', 'cns_direct_exchange')

################# Redis
# Redis Configuration
REDIS_HOST="localhost"
REDIS_PORT=6379
REDIS_DB_CACHE=0
REDIS_DB_LISTS=1
REDIS_PASSWORD="123456"
# Google Cloud Storage Configuration
GCS_BUCKET_NAME="email-checker"

# AI Service Configuration
AI_PROVIDER="gemini"
AI_MODEL_GEMINI="gemini-2.5-pro-preview-03-25"
AI_MODEL_OPENAI="gpt-4o-mini"
AI_MAX_TOKENS=65536
AI_SERVICE_PROVIDER="gemini"
AI_MICROSERVICE_URL="https://aibe.turtleit.in/api/multi-model/"

# Email Verification Service Settings
EVS_AI_DEA_CONFIDENCE_THRESHOLD=0.85
EVS_AI_ROLE_CONFIDENCE_THRESHOLD=0.80


# --- CORS ---
# Configure CORS to allow requests from your frontend
CORS_ALLOW_CREDENTIALS = True

# Explicitly list allowed origins for better security
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_ALL_ORIGINS = True

# CSRF settings
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access the cookie
CSRF_USE_SESSIONS = False  # Store CSRF token in cookie, not session
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002", 
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
    "http://127.0.0.1:8000",
]

# Allow all CORS headers and methods for development
CORS_ALLOW_ALL_ORIGINS = True  # Enable this for development to accept requests from all origins

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-platform-admin',
    'x-tenant-admin',
    'x-tenant-name',
    'X-Tenant-Admin',
    'X-Tenant-Name'
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Enable CORS for all URLs
CORS_URLS_REGEX = r'^.*$'

# --- Django Tenants Configuration ---
TENANT_MODEL = 'ecomm_superadmin.Tenant'  # app.Model containing tenant
TENANT_DOMAIN_MODEL = 'ecomm_superadmin.Domain'  # app.Model containing domains

# Tenant subfolder configuration
TENANT_SUBFOLDER_PREFIX = 'api'  # Prefix for subfolders
TENANT_SUBFOLDER_URLS = True  # Enable subfolder-based URLs

TENANT_LIMIT_SET_CALLS = False

# Configure tenant URLs
PUBLIC_SCHEMA_URLCONF = 'KeyProductSettings.urls_public'  # URLs for the public schema
ROOT_URLCONF = 'KeyProductSettings.urls'  # URLs for tenant schemas

# Function to get tenant URL
def get_tenant_url(tenant_slug):
    """
    Return the full URL for a tenant based on the current environment
    """
    if DEBUG:
        return f"http://localhost:8000/{tenant_slug}"
    else:
        return f"https://yourdomain.com/{tenant_slug}"


# --- Logging ---
# Configure logging for better debugging and production monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
       # 'file': {
       #     'level': 'INFO',
       #     'class': 'logging.FileHandler',
       #     'filename': os.path.join(BASE_DIR, 'logs/django.log'),
       #     'formatter': 'verbose',
       # },
    },
    'loggers': {
        
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django_tenants': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)
