# Generated by Django 5.0.6 on 2025-05-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_tenant_admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='company_id',
            field=models.IntegerField(blank=True, help_text='ID of the company associated with this record', null=True),
        ),
    ]
