# Generated by Django 5.0.6 on 2025-04-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_tenant_admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='ecomm_tenant_admins_userrole',
        ),
    ]
