# Generated by Django 5.0.6 on 2025-06-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_tenant_admins', '0002_userrole_client_id_userrole_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfig',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable two-factor authentication for all users'),
        ),
    ]
