# Generated by Django 5.0.6 on 2025-06-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_tenant_admins', '0003_loginconfig_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfig',
            name='app_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginconfig',
            name='theme_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
