# Generated by Django 5.0.6 on 2025-06-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_tenant_admins', '0005_loginconfig_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfig',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginconfig',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginconfig',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginconfig',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginconfig',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginconfig',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loginconfig',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loginconfig',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
