# Generated by Django 5.0.6 on 2025-06-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_tenant_admins', '0006_loginconfig_address_1_loginconfig_address_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_info', models.JSONField(default=dict, help_text='Stores core company information like name, registered address, and primary contacts.')),
                ('branding_config', models.JSONField(default=dict, help_text='Stores branding and visual identity settings like logos, colors, fonts, theme mode.')),
                ('localization_config', models.JSONField(default=dict, help_text='Stores default language, time zone, date/time formats.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True)),
                ('client_id', models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True)),
                ('company_id', models.IntegerField(blank=True, help_text='ID of the company associated with this record', null=True)),
            ],
            options={
                'verbose_name': 'Tenant Configuration',
                'verbose_name_plural': 'Tenant Configurations',
                'db_table': 'tenant_configurations',
            },
        ),
    ]
