# Generated by Django 5.0.6 on 2025-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('ClientId', models.IntegerField()),
                ('CompanyId', models.IntegerField()),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ReferredBy', models.CharField(blank=True, help_text='Name or ID of the person who referred this customer', max_length=100, null=True)),
                ('Source', models.CharField(choices=[('Existing', 'Existing'), ('Referral', 'Referral'), ('Google Ads', 'Google Ads'), ('Website', 'Website'), ('Online Portal', 'Online Portal'), ('Others', 'Others')], default='Website', max_length=20)),
                ('ChannelPartner', models.CharField(blank=True, help_text='Name of the channel partner', max_length=100, null=True)),
                ('AadharCard', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('PANCard', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Password', models.CharField(blank=True, help_text='Password for customer portal access', max_length=128, null=True)),
                ('AllowPortalAccess', models.BooleanField(default=True)),
                ('CustomerType', models.CharField(choices=[('Lead', 'Lead'), ('Disqualified Lead', 'Disqualified Lead'), ('New', 'New'), ('Active', 'Active'), ('Dormant', 'Dormant')], default='Lead', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UpdatedBy', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customers',
            },
        ),
    ]
