# Generated by Django 5.0.6 on 2025-04-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Source',
            field=models.CharField(choices=[('Existing', 'Existing'), ('Referral', 'Referral'), ('Google Ads', 'Google Ads'), ('Website', 'Website'), ('Online Portal', 'Online Portal'), ('Channel Partner/Relative', 'Channel Partner/Relative'), ('Others', 'Others')], default='Others', max_length=30),
        ),
    ]
