# Generated by Django 5.0.6 on 2025-04-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Password',
            field=models.CharField(blank=True, help_text='SHA-256 hashed password for customer portal access', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ReferredBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
