# Generated by Django 5.0.6 on 2025-04-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_password_alter_customer_referredby'),
        ('serviceagent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='AccountOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to='serviceagent.serviceagent'),
        ),
    ]
