# Generated by Django 5.2 on 2025-04-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_accountowner'),
    ]

    operations = [
    ]
