# Generated by Django 5.0.6 on 2025-05-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_backend_url',
            field=models.URLField(default='', help_text='Backend URL for the application'),
        ),
        migrations.AddField(
            model_name='application',
            name='migrate_schema_endpoint',
            field=models.CharField(default='', help_text='Home route for the application', max_length=200),
        ),
    ]
