# Generated by Django 5.0.6 on 2025-05-15 08:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0002_application_app_backend_url_and_more'),
        ('subscription_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSubscriptionLicenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('license_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('subscription_plan_snapshot', models.JSONField(help_text='Snapshot of subscription plan details at time of subscription')),
                ('features_snapshot', models.JSONField(help_text='Snapshot of features and their settings at time of subscription')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True)),
                ('company_id', models.IntegerField(blank=True, help_text='ID of the company associated with this record', null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_subscriptions', to='subscription_plan.subscriptionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='ecomm_superadmin.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Subscription License',
                'verbose_name_plural': 'Tenant Subscription Licenses',
                'db_table': 'ecomm_superadmin_tenant_subscriptions_licenses',
            },
        ),
    ]
