# Generated by Django 5.0.6 on 2025-05-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0004_lineofbusiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineofbusiness',
            name='schema_name',
        ),
    ]
