# Generated by Django 5.0.6 on 2025-05-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0005_remove_lineofbusiness_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscriptionlicenses',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One Time'), ('weekly', 'Weekly')], help_text='Billing cycle at the time of subscription', max_length=20, null=True),
        ),
    ]
