# Generated by Django 5.0.6 on 2025-05-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0006_tenantsubscriptionlicenses_billing_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='trial_end_date',
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_url',
            field=models.URLField(blank=True, help_text='Default URL for this tenant (e.g., https://tenantdomain.com)', max_length=255, null=True),
        ),
    ]
