# Generated by Django 5.0.6 on 2025-05-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0007_remove_tenant_trial_end_date_tenant_default_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='subscription_plan',
        ),
    ]
