# Generated by Django 5.0.6 on 2025-06-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0008_remove_tenant_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscriptionlicenses',
            name='access_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenantsubscriptionlicenses',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
