# Generated by Django 5.0.6 on 2025-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0009_tenantsubscriptionlicenses_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsubscriptionlicenses',
            name='access_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
