# Generated by Django 5.0.6 on 2025-06-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0010_alter_tenantsubscriptionlicenses_access_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsubscriptionlicenses',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='tenantsubscriptionlicenses',
            name='encryption_key',
        ),
    ]
