# Generated by Django 5.0.6 on 2025-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0011_remove_tenantsubscriptionlicenses_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='portals_config',
            field=models.JSONField(default=list, help_text='List of portal configurations'),
        ),
    ]
