# Generated by Django 5.0.6 on 2025-06-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0012_application_portals_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAppPortals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField()),
                ('app_id', models.IntegerField()),
                ('portal_name', models.CharField(max_length=100)),
                ('endpoint_path', models.CharField(max_length=200)),
                ('full_url', models.URLField()),
            ],
            options={
                'db_table': 'tenant_app_portals',
            },
        ),
    ]
