# Generated by Django 5.0.6 on 2025-06-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0013_tenantappportals'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenantappportals',
            table='ecomm_superadmin_tenant_app_portals',
        ),
    ]
