# Generated by Django 5.0.6 on 2025-06-07 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0014_alter_tenantappportals_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantappportals',
            old_name='full_url',
            new_name='redirect_url',
        ),
        migrations.AddField(
            model_name='tenantappportals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantappportals',
            name='created_by',
            field=models.IntegerField(blank=True, help_text='User who created this record', null=True),
        ),
        migrations.AddField(
            model_name='tenantappportals',
            name='custom_redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantappportals',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenantappportals',
            name='updated_by',
            field=models.IntegerField(blank=True, help_text='User who last updated this record', null=True),
        ),
    ]
