# Generated by Django 5.0.6 on 2025-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0015_rename_full_url_tenantappportals_redirect_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantappportals',
            name='default_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
