# Generated by Django 5.0.6 on 2025-06-19 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0016_tenantappportals_default_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='url_suffix',
            field=models.CharField(blank=True, help_text='Custom URL suffix for this tenant (e.g., "company_name" for company_name.example.com). Only letters, numbers, hyphens, and underscores are allowed.', max_length=63, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_url_suffix', message='URL suffix can only contain letters, numbers, hyphens, and underscores.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
