# Generated by Django 5.0.6 on 2025-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAgent',
            fields=[
                ('serviceagentid', models.AutoField(primary_key=True, serialize=False)),
                ('serviceagentname', models.CharField(max_length=100)),
                ('emailid', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('allowportalaccess', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('clientid', models.IntegerField(default=1)),
                ('companyid', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Service Agent',
                'verbose_name_plural': 'Service Agents',
                'db_table': 'serviceagent',
                'ordering': ['serviceagentname'],
            },
        ),
    ]
