# Generated by Django 5.0.6 on 2025-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceagent', '0001_initial'),
        ('servicecategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceagent',
            name='expertat',
            field=models.ManyToManyField(blank=True, related_name='service_agents', to='servicecategory.servicecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceagent',
            unique_together={('clientid', 'companyid', 'serviceagentname')},
        ),
    ]
