# Generated by Django 5.0.6 on 2025-04-22 05:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('serviceagent', '0002_initial'),
        ('servicecategory', '0002_initial'),
        ('sop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('serviceticketid', models.AutoField(primary_key=True, serialize=False)),
                ('clientid', models.IntegerField(default=1)),
                ('companyid', models.IntegerField(default=1)),
                ('serviceticketsubject', models.CharField(max_length=255)),
                ('serviceticketdesc', models.TextField(blank=True, null=True)),
                ('creationdate', models.DateField(default=datetime.date.today)),
                ('targetclosuredate', models.DateField(null=True)),
                ('status', models.CharField(default='New', max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('updatedby', models.CharField(max_length=255, null=True)),
                ('customerid', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('serviceagentid', models.ForeignKey(blank=True, db_column='serviceagentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceagent.serviceagent')),
                ('servicecategoryid', models.ForeignKey(blank=True, db_column='servicecategoryid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicecategory.servicecategory')),
            ],
            options={
                'db_table': 'serviceticket',
                'ordering': ['-createdat'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket_Tasks',
            fields=[
                ('Client_Id', models.IntegerField(default=1)),
                ('Company_Id', models.IntegerField(default=1)),
                ('ServiceTicketTaskId', models.AutoField(primary_key=True, serialize=False)),
                ('Sequence', models.IntegerField()),
                ('TaskName', models.CharField(max_length=255)),
                ('TaskStartDate', models.DateField(blank=True, null=True)),
                ('TaskClosureDate', models.DateField(blank=True, null=True)),
                ('TaskStatus', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('InProgress', 'In Progress'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('Createdat', models.DateTimeField(auto_now_add=True)),
                ('Createdby', models.CharField(max_length=255)),
                ('Updatedat', models.DateTimeField(auto_now=True)),
                ('Updatedby', models.CharField(blank=True, max_length=255, null=True)),
                ('SOPStepID', models.ForeignKey(blank=True, db_column='SOPStepID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sop.sopsteps')),
                ('ServiceTicketId', models.ForeignKey(db_column='ServiceTicketId', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='servicetickets.serviceticket')),
                ('TaskServiceAgent', models.ForeignKey(blank=True, db_column='TaskServiceAgent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceagent.serviceagent')),
            ],
            options={
                'db_table': 'serviceticket_tasks',
                'ordering': ['ServiceTicketId', 'Sequence'],
            },
        ),
    ]
