# Generated by Django 5.0.6 on 2025-04-22 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('ClientId', models.IntegerField(default=1)),
                ('CompanyId', models.IntegerField(default=1)),
                ('CredentialTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('CredentialTypeName', models.CharField(max_length=100)),
                ('URL', models.URLField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UpdatedBy', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Credential Type',
                'verbose_name_plural': 'Credential Types',
                'db_table': 'CredentialTypes',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('ClientId', models.IntegerField(default=1)),
                ('CompanyId', models.IntegerField(default=1)),
                ('CredentialId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UpdatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('EmailOTP', models.CharField(blank=True, max_length=255, null=True)),
                ('MobileOTP', models.CharField(blank=True, max_length=255, null=True)),
                ('CustomerId', models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='customers.customer')),
                ('CredentialTypeId', models.ForeignKey(db_column='CredentialTypeId', on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='credentials.credentialtype')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'db_table': 'Credentials',
            },
        ),
    ]
