# Generated by Django 5.2 on 2025-05-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_controles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant User',
                'verbose_name_plural': 'Tenant Users',
                'db_table': 'ecomm_tenant_admins_tenantuser',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='userroleassignment',
            options={'ordering': ['user', 'role__name'], 'verbose_name': 'User Role Assignment', 'verbose_name_plural': 'User Role Assignments'},
        ),
        migrations.AlterField(
            model_name='userroleassignment',
            name='user',
            field=models.IntegerField(db_index=True, verbose_name='User ID'),
        ),
    ]
