# Generated by Django 5.2 on 2025-05-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_controles', '0002_tenantuser_alter_userroleassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='last_modified_by',
            field=models.IntegerField(default=1),
        ),
    ]
