# Generated by Django 5.2 on 2025-05-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_controles', '0003_alter_role_created_by_alter_role_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissionset',
            name='app_id',
            field=models.IntegerField(blank=True, help_text='ID of the app/module from my_features.ts', null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='app_id',
            field=models.IntegerField(blank=True, help_text='ID of the app/module from my_features.ts', null=True),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='app_id',
            field=models.IntegerField(blank=True, help_text='ID of the app/module from my_features.ts', null=True),
        ),
    ]
