# Generated by Django 5.2 on 2025-05-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_controles', '0005_remove_role_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermissionset',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulepermissionset',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
