# Generated by Django 5.0.6 on 2025-04-22 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPMaster',
            fields=[
                ('ClientId', models.IntegerField(default=1)),
                ('CompanyId', models.IntegerField(default=1)),
                ('SOPId', models.AutoField(primary_key=True, serialize=False)),
                ('SOPName', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Version', models.IntegerField(default=1)),
                ('VersionEffectiveDate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UpdatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('ProcessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sops', to='process.processmaster')),
            ],
            options={
                'verbose_name': 'SOP',
                'verbose_name_plural': 'SOPs',
                'db_table': 'SOPMaster',
                'unique_together': {('ProcessId', 'Version')},
            },
        ),
        migrations.CreateModel(
            name='SOPSteps',
            fields=[
                ('ClientId', models.IntegerField(default=1)),
                ('CompanyId', models.IntegerField(default=1)),
                ('StepId', models.AutoField(primary_key=True, serialize=False)),
                ('Sequence', models.IntegerField(default=1)),
                ('StepName', models.CharField(max_length=255)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('Prerequisites', models.TextField(blank=True, null=True)),
                ('Postrequisites', models.TextField(blank=True, null=True)),
                ('DocumentPath', models.CharField(blank=True, max_length=500, null=True)),
                ('OriginalFileName', models.CharField(blank=True, max_length=255, null=True)),
                ('FileName', models.CharField(blank=True, max_length=255, null=True)),
                ('URL', models.CharField(blank=True, max_length=500, null=True)),
                ('Duration', models.IntegerField(default=1)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UpdatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('SOPId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sop.sopmaster')),
            ],
            options={
                'verbose_name': 'SOP Step',
                'verbose_name_plural': 'SOP Steps',
                'db_table': 'SOPSteps',
                'ordering': ['Sequence', 'StepId'],
            },
        ),
    ]
