# Generated by Django 5.0.6 on 2025-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMaster',
            fields=[
                ('ClientId', models.IntegerField(default=1)),
                ('CompanyId', models.IntegerField(default=1)),
                ('ProcessId', models.AutoField(primary_key=True, serialize=False)),
                ('ProcessName', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('ProcessAudience', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], default='Individual', max_length=20)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UpdatedBy', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'db_table': 'ProcessMaster',
            },
        ),
    ]
